### ISSUE TITLE
i hava a error in line 158

### ISSUE THREAD

**Issue by wooyunvip** [Hell0W0rld0/Github-Hunter#2]
such as:
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "GithubHunter.py", line 158, in <module>
    sensitive_list,comp_list = hunter(g_User, g_Pass, keyword, payloads)
TypeError: 'NoneType' object is not iterable

how to fix it

**Comment by wooyunvip** [comment]
fix it

**Comment by xiaosaoba** [comment]
a error in 144：

Traceback (most recent call last):
  File "GithubHunter.py", line 144, in <module>
    g_User = config['Github']['user']
  File "/usr/local/python3/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'Github'

**Comment by Hell0W0rld0** [comment]
> fix it

Ok ,thanks

**Comment by iDjorik** [comment]
Nowadays thus error is at line 188:

'latin-1' codec can't encode characters in position 0-12: ordinal not in range(256)
Traceback (most recent call last):
  File "GithubHunter.py", line 188, in <module>
    tUrls, codes= hunter(g_User, g_Pass, keywords)
TypeError: 'NoneType' object is not iterable
