### ISSUE TITLE
a error in line 144

### ISSUE THREAD

**Issue by xiaosaoba** [Hell0W0rld0/Github-Hunter#3]
Traceback (most recent call last):
  File "GithubHunter.py", line 144, in <module>
    g_User = config['Github']['user']
  File "/usr/local/python3/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'Github'

**Comment by secitSdr** [comment]
去掉配置文件的example。

**Comment by Hell0W0rld0** [comment]
> 去掉配置文件的example。

Great!
